apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sosyal-kuran
resources:
  - namespace.yaml
  - cnpg-cluster.yaml
  - redis.yaml
  - quran-data.yaml
  - keycloak.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml
configMapGenerator:
  - name: keycloak-realm
    files:
      - sosyal-kuran-realm.json=keycloak-realm.json
  - name: keycloak-theme
    files:
      - theme.properties=keycloak-theme/theme.properties
      - sosyal-kuran.css=keycloak-theme/sosyal-kuran.css
      - brand.js=keycloak-theme/brand.js
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: ghcr.io/mehmetcolgecen/sosyal-kuran-web
    newTag: latest
  - name: ghcr.io/mehmetcolgecen/sosyal-kuran-api
    newTag: latest
  - name: ghcr.io/mehmetcolgecen/sosyal-kuran-data
    newTag: latest
